### ISSUE TITLE
Missing the most recent content

### ISSUE THREAD

**Issue by Lazloo** [JackMcKew/awesome-python-bytes#16]
Hey,

Great project. I appreciate your work very much. I start to use your project as one of my main sources to find python packages that solve my issues!

In which periods will the repository updated. I recognize that content from episode 183 and later is missing (e.g.  "Schemathesis").

THX
Lazloo

**Comment by JackMcKew** [comment]
Hi @Lazloo 

Thank you so much, and fantastic that you are using it as a resource!

I started this repository with only the packages that I heard about on Python Bytes that I **personally** thought were noteworthy and interesting, rather than all packages.

If you heard about a package or project that **you** thought was interesting, pull requests are more than welcome to add it to the list!
